package jarvis.tutor

import jarvis.Config
import jarvis.CoreMemory
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption
import java.security.MessageDigest
import java.time.Instant
import kotlin.io.path.createDirectories
import kotlin.io.path.exists
import kotlin.io.path.readText

/**
 * Tutor task-context V1 (Stage D) — Karpathy LLM Wiki page-per-concept.
 *
 * Inspiration: Karpathy 2026-04 LLM Wiki gist + lucasastorian/llmwiki
 * + Astro-Han/karpathy-llm-wiki + skyllwt/OmegaWiki. Each concept gets
 * a markdown page that the tutor APPENDS to over time as it learns
 * what the user has questioned, struggled with, mastered.
 *
 * NOT a graph (KnowledgeGraph already covers cross-concept structural
 * edges). NOT a chat log (Conversations already covers raw turns). The
 * wiki is the LLM's evolving model of THIS user's understanding of
 * THIS concept — what they confused it with, what worked to clarify,
 * which prereqs they needed.
 *
 * Layout: <archivalRoot>/_wiki/<subject>/<concept-slug>.md
 *
 * Filename slug: lowercased concept, non-alpha → '-', squashed runs.
 * Subject directory mirrors the archival subject naming.
 *
 * File format (each page is a self-contained markdown doc):
 *
 *   ---
 *   concept: Greedy algorithm
 *   subject: PA
 *   first_touched: 2026-05-01T10:00:00Z
 *   last_updated: 2026-05-09T14:32:00Z
 *   touch_count: 7
 *   ---
 *
 *   # Greedy algorithm
 *
 *   ## Brief
 *   <auto-generated summary>
 *
 *   ## Confusions
 *   - 2026-05-03: confused with dynamic programming when prefix sums hint
 *   - 2026-05-07: thought activity selection used DP
 *
 *   ## Worked clarifications
 *   - 2026-05-04: greedy choice property explained via change-making
 *
 *   ## Prereqs needed
 *   - sorting (sort by end-time was the unlock)
 *
 *   ## Last user state
 *   - confidence rising, stale 2d (2026-05-09 read)
 *
 * Append-only sections — never rewrites prior bullets. PII filter via
 * CoreMemory.scanTextForPii on every appended bullet.
 */
@Serializable
data class WikiSection(val name: String, val bullets: List<String> = emptyList())

object WikiPage {

    fun root(archivalRoot: Path = Config.archivalDir): Path =
        archivalRoot.resolve("_wiki")

    fun pageFor(subject: String, concept: String, archivalRoot: Path = Config.archivalDir): Path =
        root(archivalRoot).resolve(subject).resolve(slug(concept) + ".md")

    /** Read the whole page as text; null when missing. */
    fun read(subject: String, concept: String, archivalRoot: Path = Config.archivalDir): String? {
        val p = pageFor(subject, concept, archivalRoot)
        if (!p.exists()) return null
        return try { p.readText(Charsets.UTF_8) } catch (_: Exception) { null }
    }

    /** Append a bullet to the named section, creating the page (and
     *  the section) if absent. Bullet is PII-scrubbed; rejected with
     *  WARN if it trips a finding. Frontmatter touch_count bumps. */
    fun append(
        subject: String,
        concept: String,
        section: String,
        bullet: String,
        archivalRoot: Path = Config.archivalDir,
        now: Instant = Instant.now(),
    ): Boolean {
        val cleanBullet = bullet.trim().replace('\n', ' ')
        if (cleanBullet.isEmpty()) return false
        val pii = CoreMemory.scanTextForPii(cleanBullet)
        if (pii.isNotEmpty()) {
            System.err.println("[WikiPage] WARN dropping bullet for $subject/$concept — PII: ${pii.joinToString { it.kind }}")
            return false
        }
        val timestamped = "- ${now.toString().take(19)}: ${cleanBullet.take(400)}"

        val page = pageFor(subject, concept, archivalRoot)
        page.parent?.createDirectories()

        val text = if (page.exists()) page.readText(Charsets.UTF_8) else newPage(subject, concept, now)
        val updated = ensureSection(text, section, timestamped, now)
        // StateVersion bump so any cached TaskHeader reads see fresh wiki touch.
        StateVersion.bump()
        Files.writeString(
            page, updated, Charsets.UTF_8,
            StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE,
        )
        return true
    }

    /** List every wiki page (subject + concept + path) for indexing. */
    fun list(archivalRoot: Path = Config.archivalDir): List<Triple<String, String, Path>> {
        val r = root(archivalRoot)
        if (!r.exists()) return emptyList()
        val out = mutableListOf<Triple<String, String, Path>>()
        Files.walk(r).use { stream ->
            stream.filter { it.toString().endsWith(".md") }.forEach { path ->
                val rel = r.relativize(path).toString().replace('\\', '/')
                val parts = rel.split('/')
                if (parts.size != 2) return@forEach
                val subject = parts[0]
                val concept = parts[1].removeSuffix(".md")
                    .replace('-', ' ')
                out += Triple(subject, concept, path)
            }
        }
        return out
    }

    internal fun slug(concept: String): String {
        val lower = concept.lowercase()
        val replaced = StringBuilder()
        var lastDash = false
        for (c in lower) {
            if (c.isLetterOrDigit()) {
                replaced.append(c); lastDash = false
            } else if (!lastDash) {
                replaced.append('-'); lastDash = true
            }
        }
        // Trim leading/trailing dashes; cap at 80 chars.
        return replaced.toString().trim('-').take(80).ifEmpty { sha8(concept) }
    }

    private fun sha8(s: String): String {
        val md = MessageDigest.getInstance("SHA-256")
        return md.digest(s.toByteArray(Charsets.UTF_8))
            .joinToString("") { "%02x".format(it) }.take(8)
    }

    private fun newPage(subject: String, concept: String, now: Instant): String = """
        |---
        |concept: $concept
        |subject: $subject
        |first_touched: $now
        |last_updated: $now
        |touch_count: 0
        |---
        |
        |# $concept
        |
        |## Brief
        |
    """.trimMargin() + "\n"

    /** Append [timestamped] under the [section]; create the section
     *  if missing. Bumps frontmatter `last_updated` + `touch_count`. */
    internal fun ensureSection(text: String, section: String, timestamped: String, now: Instant): String {
        val withSection = if (text.contains("\n## $section")) text else
            text.trimEnd() + "\n\n## $section\n"
        val withBullet = withSection.trimEnd() + "\n$timestamped\n"
        return bumpFrontmatter(withBullet, now)
    }

    private fun bumpFrontmatter(text: String, now: Instant): String {
        val nowStr = now.toString()
        val touchRe = Regex("""(?m)^touch_count:\s*(\d+)$""")
        val updatedRe = Regex("""(?m)^last_updated:\s*[^\n]+$""")
        var out = text
        val touchMatch = touchRe.find(out)
        out = if (touchMatch != null) {
            val newCount = (touchMatch.groupValues[1].toIntOrNull() ?: 0) + 1
            touchRe.replace(out, "touch_count: $newCount")
        } else out
        out = if (updatedRe.containsMatchIn(out))
            updatedRe.replace(out, "last_updated: $nowStr")
        else out
        return out
    }
}
