# Install/rotate the jarvis PC-relay server as a Windows scheduled task.
#
# What this does:
#   1. Stops any python process currently listening on port 9999.
#   2. Generates a fresh 64-hex bearer token.
#   3. Persists token to a 0700-perm file at ~/.jarvis-relay-token.
#   4. Writes a VBS launcher that reads the token file + execs pythonw.
#   5. Registers schtask 'JarvisRelayServer' to fire at user logon.
#   6. Starts the task now and smoke-checks /healthz.
#   7. Copies the new token into the clipboard for VPS update.
#
# Run from any PowerShell session in this directory:
#   .\install-pc-relay.ps1
#
# Uninstall:
#   .\install-pc-relay.ps1 -Uninstall

param(
    [switch]$Uninstall
)

$TaskName  = "JarvisRelayServer"
$ToolsDir  = "C:\Users\User\jarvis-kotlin\tools"
$VbsPath   = Join-Path $ToolsDir "start_relay_hidden.vbs"
$ServerPy  = Join-Path $ToolsDir "pc-relay-server.py"
$TokenFile = Join-Path $env:USERPROFILE ".jarvis-relay-token"

if ($Uninstall) {
    schtasks /Delete /TN $TaskName /F 2>$null
    Remove-Item $TokenFile -ErrorAction SilentlyContinue
    Remove-Item $VbsPath  -ErrorAction SilentlyContinue
    Write-Host "Uninstalled $TaskName + cleared $TokenFile + $VbsPath"
    exit 0
}

if (-not (Test-Path $ServerPy)) {
    Write-Error "Relay server missing: $ServerPy"
    exit 1
}

# 1. Kill anything currently bound to 9999 so the task can take it.
$listener = Get-NetTCPConnection -LocalPort 9999 -ErrorAction SilentlyContinue |
    Where-Object { $_.State -eq 'Listen' }
if ($listener) {
    foreach ($conn in $listener) {
        Write-Host "Stopping existing process on :9999 (pid $($conn.OwningProcess))"
        Stop-Process -Id $conn.OwningProcess -Force -ErrorAction SilentlyContinue
    }
    Start-Sleep -Seconds 2
}

# 2. Generate fresh token (64 hex chars).
$tok = -join ((1..64) | ForEach-Object { [char]((48..57) + (97..102) | Get-Random) })

# 3. Persist to user-only file. icacls strips inheritance + grants only the
#    current user - so other accounts on this box (if any) can't read it.
Set-Content -Path $TokenFile -Value $tok -Encoding ASCII -NoNewline
icacls $TokenFile /inheritance:r /grant:r "${env:USERNAME}:F" | Out-Null

# 4. Write VBS launcher. Reads token from file, sets it as a process env
#    var, runs pythonw with no console window. Async (third arg False).
$vbsContent = @'
' Auto-generated by install-pc-relay.ps1. Edit there, not here.
Set fso = CreateObject("Scripting.FileSystemObject")
Set ts = fso.OpenTextFile("C:\Users\User\.jarvis-relay-token", 1)
tok = Trim(ts.ReadAll())
ts.Close

Set sh = CreateObject("WScript.Shell")
sh.Environment("Process").Item("JARVIS_RELAY_TOKEN") = tok
sh.Environment("Process").Item("JARVIS_RELAY_LOG") = "C:\Users\User\.jarvis-relay.log"
sh.Run """pythonw.exe"" ""C:\Users\User\jarvis-kotlin\tools\pc-relay-server.py""", 0, False
Set sh = Nothing
'@
Set-Content -Path $VbsPath -Value $vbsContent -Encoding ASCII

# 5. Register at-logon task. /F overwrites prior install of the same name.
schtasks /Create `
    /TN $TaskName `
    /TR "wscript.exe `"$VbsPath`"" `
    /SC ONLOGON `
    /RL LIMITED `
    /F | Out-Null

if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to register scheduled task."
    exit $LASTEXITCODE
}

# 6. Start it now and smoke-check.
schtasks /Run /TN $TaskName | Out-Null
Start-Sleep -Seconds 4
$code = curl.exe -s -o NUL -w "%{http_code}" -H "Authorization: Bearer $tok" http://localhost:9999/healthz

if ($code -ne "200") {
    Write-Warning "Relay /healthz returned $code. Inspect Task Scheduler -> $TaskName -> History."
    exit 1
}

Write-Host "Relay running under $TaskName. /healthz=200."

# 7. Hand the token off via clipboard.
$tok | Set-Clipboard
Write-Host ""
Write-Host "Token copied to clipboard."
Write-Host "SSH to VPS and run (paste at the marked spot):"
Write-Host ""
Write-Host '  ssh root@46.247.109.91'
Write-Host '  TOK="<paste>"'
Write-Host '  sed -i "s|^JARVIS_RELAY_TOKEN=.*|JARVIS_RELAY_TOKEN=$TOK|" /opt/jarvis/.env'
Write-Host '  systemctl restart jarvis'
Write-Host '  unset TOK; history -c'
Write-Host ""
Write-Host "Token also persisted at: $TokenFile (user-only)"
