#!/usr/bin/env python3
"""One-time bulk scrape of SO + RC course material from UAIC.

Fetches everything listed in the inventory crawl 2026-05-09:

- 50 SO PDFs from https://edu.info.uaic.ro/operating-systems-and-computer-networks/SO/
  (auth so2026:i+a=IA): 28 lecture PDFs (print + web variants), 9 ManualID
  chapters, 8 textbooks (Tanenbaum/Silberschatz/Stevens/Kerrisk/etc.), 3 docs,
  2 lecture-demo support PDFs.
- ~30 SO HTML pages: idx_teaching, idx_exam, idx_bib, idx_OS-team, EVP,
  web-resources, plus support-lessons + demos + labs.
- 14 RC PDFs from https://profs.info.uaic.ro/georgiana.calancea/ (no auth):
  3 Curs PPT-PDFs, 11 Laboratorul_*.pdf, Bash Pocket Reference.
- 7 RC HTML pages: so-rc-home, rc-home, evaluation, laboratories, schedule,
  so-rc-evaluation, so-rc-laboratories.

Each URL → (binary file) + (.md text-extract) saved to OUT_DIR. PDFs go
through pdftotext (which must be on PATH); HTML files get a regex tag-strip.
Failures append to a `_failures.log` rather than aborting.

Usage:
    python3 tools/scrape-so-rc-content.py [OUT_DIR=./tmp-so-rc-scrape]

After the run, scp the OUT_DIR contents to
/opt/jarvis/data/archival/_extras/{SO,RC}/ on the VPS — see the wrapping
script tools/upload-so-rc-content.sh (also generated by hand for this
one-shot job).

Heuristic: --skip-existing on by default. Re-runs in a populated OUT_DIR
skip already-downloaded files to amortize a slow connection across
multiple sessions if the downloads get interrupted.
"""

from __future__ import annotations

import base64
import os
import re
import subprocess
import sys
import time
import urllib.error
import urllib.parse
import urllib.request
from html import unescape
from pathlib import Path

OUT_DIR = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("./tmp-so-rc-scrape")
SKIP_EXISTING = "--no-skip-existing" not in sys.argv

SO_BASE = "https://edu.info.uaic.ro/operating-systems-and-computer-networks/SO/"
SO_AUTH = "Basic " + base64.b64encode(b"so2026:i+a=IA").decode("ascii")
RC_BASE = "https://profs.info.uaic.ro/georgiana.calancea/"

# Per inventory-crawl 2026-05-09. Each tuple = (relative URL under base, kind)
# kind = "pdf" | "html" | "chm" (chm skipped — no extractor).
SO_FILES: list[tuple[str, str]] = [
    # Top-level + idx pages
    ("index.html", "html"),
    ("idx_teaching.html", "html"),
    ("idx_exam.html", "html"),
    ("idx_bib.html", "html"),
    ("idx_OS-team.html", "html"),
    ("idx_news.html", "html"),
    ("menu-top_nav.html", "html"),
    ("web-resources.html", "html"),
    ("EVP/proba_LinuxInstall.html", "html"),
    # 28 lecture PDFs
    ("lectures/Install_guide.pdf", "pdf"),
    ("lectures/Mini-ghid_instalare_WSL2.pdf", "pdf"),
    ("lectures/OS1.1_Linux-intro_print-ro.pdf", "pdf"),
    ("lectures/OS1.1_Linux-intro_web-ro.pdf", "pdf"),
    ("lectures/OS1.2_commands_print-ro.pdf", "pdf"),
    ("lectures/OS1.2_commands_web-ro.pdf", "pdf"),
    ("lectures/OS1.3_WSL1&WSL2_ppt-ro.pdf", "pdf"),
    ("lectures/OS2.1_shell1_print-ro.pdf", "pdf"),
    ("lectures/OS2.1_shell1_web-ro.pdf", "pdf"),
    ("lectures/OS2.2_shell2_print-ro.pdf", "pdf"),
    ("lectures/OS2.2_shell2_web-ro.pdf", "pdf"),
    ("lectures/OS2.3_X-Window_ppt-ro.pdf", "pdf"),
    ("lectures/OS3.1_files_print-ro.pdf", "pdf"),
    ("lectures/OS3.1_files_web-ro.pdf", "pdf"),
    ("lectures/OS3.2_flock_print-ro.pdf", "pdf"),
    ("lectures/OS3.2_flock_web-ro.pdf", "pdf"),
    ("lectures/OS4.1_fork+wait_print-ro.pdf", "pdf"),
    ("lectures/OS4.1_fork+wait_web-ro.pdf", "pdf"),
    ("lectures/OS4.2_exec_print-ro.pdf", "pdf"),
    ("lectures/OS4.2_exec_web-ro.pdf", "pdf"),
    ("lectures/OS5_mmap_print-ro.pdf", "pdf"),
    ("lectures/OS5_mmap_web-ro.pdf", "pdf"),
    ("lectures/OS6_pipe+fifo_print-ro.pdf", "pdf"),
    ("lectures/OS6_pipe+fifo_web-ro.pdf", "pdf"),
    ("lectures/OS7.1_signals_print-ro.pdf", "pdf"),
    ("lectures/OS7.1_signals_web-ro.pdf", "pdf"),
    ("lectures/OS7.2_ncurses_print-ro.pdf", "pdf"),
    ("lectures/OS7.2_ncurses_web-ro.pdf", "pdf"),
    # docs / cheatsheets
    ("docs/OS-Cheatsheet.pdf", "pdf"),
    ("note/SO&RC 2026 OVERVIEW - componenta SO.pdf", "pdf"),
    # 8 textbooks
    ("books/APUE3.pdf", "pdf"),
    ("books/BPR1.pdf", "pdf"),
    ("books/MOS5.pdf", "pdf"),
    ("books/ManualID-SO.pdf", "pdf"),
    ("books/OSC10.pdf", "pdf"),
    ("books/OSDI3.chm", "chm"),
    ("books/OSIDP7.pdf", "pdf"),
    ("books/TLPI1.pdf", "pdf"),
    # 9 ManualID chapters
    ("books/ManualID-SO_chapters/fork+wait+exec.pdf", "pdf"),
    ("books/ManualID-SO_chapters/compiler.pdf", "pdf"),
    ("books/ManualID-SO_chapters/file+lock.pdf", "pdf"),
    ("books/ManualID-SO_chapters/pipe+fifo.pdf", "pdf"),
    ("books/ManualID-SO_chapters/command.pdf", "pdf"),
    ("books/ManualID-SO_chapters/filesys.pdf", "pdf"),
    ("books/ManualID-SO_chapters/distros.pdf", "pdf"),
    ("books/ManualID-SO_chapters/intro.pdf", "pdf"),
    ("books/ManualID-SO_chapters/shellprg.pdf", "pdf"),
    # 2 demo bib PDFs
    ("lectures/demo/suport-curs3_bib1_fs-cache.pdf", "pdf"),
    ("lectures/demo/suport-curs3_bib2_stdio.pdf", "pdf"),
    ("lectures/demo/suport-curs5_bib_sync-patterns.pdf", "pdf"),
    # Labs (HTML)
    ("labs/C/lab4.html", "html"),
    ("labs/C/lab5.html", "html"),
    ("labs/C/lab6.html", "html"),
    ("labs/C/lab7.html", "html"),
    ("labs/C/lab7b.html", "html"),
    ("labs/bash/lab1.html", "html"),
    ("labs/bash/lab2.html", "html"),
    ("labs/bash/lab3.html", "html"),
    # Demos (HTML)
    ("lectures/demo/exec/idx_demo.html", "html"),
    ("lectures/demo/files/idx_demo.html", "html"),
    ("lectures/demo/flock/idx_demo.html", "html"),
    ("lectures/demo/fork/idx_demo.html", "html"),
    ("lectures/demo/mmap/idx_demo.html", "html"),
    ("lectures/demo/ncurses/idx_demo.html", "html"),
    ("lectures/demo/pipe/idx_demo.html", "html"),
    ("lectures/demo/signals/idx_demo.html", "html"),
    # Support lessons (HTML)
    ("support-lessons/C/suport_lab4.html", "html"),
    ("support-lessons/C/suport_lab5.html", "html"),
    ("support-lessons/C/suport_lab6.html", "html"),
    ("support-lessons/C/suport_lab7.html", "html"),
    ("support-lessons/C/suport_lab7b.html", "html"),
    ("support-lessons/C/suport_lab7c.html", "html"),
    ("support-lessons/bash/suport_lab1.html", "html"),
    ("support-lessons/bash/suport_lab2.html", "html"),
    ("support-lessons/bash/suport_lab3.html", "html"),
]

RC_FILES: list[tuple[str, str]] = [
    # 7 HTML pages
    ("so-rc-home.html", "html"),
    ("rc-home.html", "html"),
    ("evaluation.html", "html"),
    ("laboratories.html", "html"),
    ("schedule.html", "html"),
    ("so-rc-evaluation.html", "html"),
    ("so-rc-laboratories.html", "html"),
    # 14 PDFs
    ("Curs1_De_la_procese_la_retele_RO.pptx.pdf", "pdf"),
    ("Curs2_Programare_in_retea_1.pptx.pdf", "pdf"),
    ("Curs3_Programare_in_retea_2.pptx.pdf", "pdf"),
    ("Laboratorul_1.pdf", "pdf"),
    ("Laboratorul_2.pdf", "pdf"),
    ("Laboratorul_3.pdf", "pdf"),
    ("Laboratorul_4.pdf", "pdf"),
    ("Laboratorul_6.pdf", "pdf"),
    ("Laboratorul_7.pdf", "pdf"),
    ("Laboratorul_9.pdf", "pdf"),
    ("Laboratorul_10.pdf", "pdf"),
    ("Laboratorul_12.pdf", "pdf"),
    ("Laboratorul_13.pdf", "pdf"),
    ("Oreilly.Bash.Pocket.Reference.May.2010.pdf", "pdf"),
]


def _safe_name(rel: str) -> str:
    """Convert URL-relative path to a flat filename safe for any FS."""
    # Replace path separators + URL-unsafe chars
    name = rel.replace("/", "__").replace(" ", "_")
    # Some paths have "&" / "+" — keep them for human-readability, but strip
    # Windows-disallowed chars.
    return re.sub(r'[<>:"|?*]', "_", name)


def fetch(url: str, auth: str | None, dest: Path) -> tuple[bool, int]:
    if SKIP_EXISTING and dest.exists() and dest.stat().st_size > 0:
        return (True, dest.stat().st_size)
    headers = {"User-Agent": "jarvis-so-rc-scrape/1.0"}
    if auth:
        headers["Authorization"] = auth
    req = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:
            data = resp.read()
    except (urllib.error.HTTPError, urllib.error.URLError, TimeoutError) as e:
        return (False, 0)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(data)
    return (True, len(data))


def html_to_text(html: str) -> str:
    no_script = re.sub(r"<script[^>]*>.*?</script>", " ", html, flags=re.DOTALL | re.IGNORECASE)
    no_style = re.sub(r"<style[^>]*>.*?</style>", " ", no_script, flags=re.DOTALL | re.IGNORECASE)
    no_tags = re.sub(r"<[^>]+>", " ", no_style)
    decoded = unescape(no_tags)
    return re.sub(r"\s+", " ", decoded).strip()


def pdf_to_text(pdf_path: Path) -> str:
    """Run pdftotext (poppler) on the file, return UTF-8 text or empty."""
    try:
        proc = subprocess.run(
            ["pdftotext", "-layout", "-enc", "UTF-8", str(pdf_path), "-"],
            capture_output=True, timeout=120,
        )
        if proc.returncode == 0:
            return proc.stdout.decode("utf-8", errors="replace")
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass
    # Fallback: PyPDF2.
    try:
        import PyPDF2
        reader = PyPDF2.PdfReader(str(pdf_path))
        return "\n\n".join(p.extract_text() or "" for p in reader.pages)
    except Exception:
        return ""


def process(items: list[tuple[str, str]], base: str, auth: str | None,
            sub_dir: Path, label: str, failures: list[str]) -> tuple[int, int, int]:
    sub_dir.mkdir(parents=True, exist_ok=True)
    fetched = converted = skipped = 0
    for rel, kind in items:
        if kind == "chm":
            skipped += 1
            continue
        url = base + urllib.parse.quote(rel, safe="/-_.+&")
        bin_name = _safe_name(rel)
        bin_path = sub_dir / bin_name
        ok, size = fetch(url, auth, bin_path)
        if not ok:
            failures.append(f"{label}: fetch failed: {url}")
            continue
        fetched += 1
        # Convert to .md if not already done
        md_name = bin_name.rsplit(".", 1)[0] + ".md"
        md_path = sub_dir / md_name
        if SKIP_EXISTING and md_path.exists() and md_path.stat().st_size > 0:
            converted += 1
            continue
        if kind == "pdf":
            text = pdf_to_text(bin_path)
        elif kind == "html":
            text = html_to_text(bin_path.read_text(encoding="utf-8", errors="replace"))
        else:
            text = ""
        if text:
            md_path.write_text(text + "\n", encoding="utf-8")
            converted += 1
        else:
            failures.append(f"{label}: text extract empty: {rel}")
    return fetched, converted, skipped


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    so_dir = OUT_DIR / "SO"
    rc_dir = OUT_DIR / "RC"
    failures: list[str] = []
    t0 = time.time()
    so_fetched, so_md, so_skipped = process(SO_FILES, SO_BASE, SO_AUTH, so_dir, "SO", failures)
    rc_fetched, rc_md, rc_skipped = process(RC_FILES, RC_BASE, None, rc_dir, "RC", failures)
    elapsed = time.time() - t0
    if failures:
        (OUT_DIR / "_failures.log").write_text(
            "\n".join(failures) + "\n", encoding="utf-8"
        )
    print(f"SO: fetched={so_fetched} md_extracted={so_md} skipped(chm)={so_skipped}")
    print(f"RC: fetched={rc_fetched} md_extracted={rc_md} skipped={rc_skipped}")
    print(f"Failures: {len(failures)} (see {OUT_DIR}/_failures.log)")
    print(f"Total elapsed: {elapsed:.1f}s — files at {OUT_DIR.resolve()}")


if __name__ == "__main__":
    main()
