' Auto-generated by install-pc-relay.ps1. Edit there, not here.
Set fso = CreateObject("Scripting.FileSystemObject")
Set ts = fso.OpenTextFile("C:\Users\User\.jarvis-relay-token", 1)
tok = Trim(ts.ReadAll())
ts.Close

Set sh = CreateObject("WScript.Shell")
sh.Environment("Process").Item("JARVIS_RELAY_TOKEN") = tok
sh.Environment("Process").Item("JARVIS_RELAY_LOG") = "C:\Users\User\.jarvis-relay.log"
sh.Run """pythonw.exe"" ""C:\Users\User\jarvis-kotlin\tools\pc-relay-server.py""", 0, False
Set sh = Nothing
