#!/usr/bin/env bash
# Idempotent VPS installer for jarvis-kotlin. Run as root on Ubuntu 22.04.
# Assumes JDK 21, Node 20+, npm, and an existing nginx are already in place
# (matches the panel.* VPS layout probed 2026-05-07).
#
# What this script does:
#   1. Verifies JDK 21 + Node 20+
#   2. Installs claude CLI globally if missing (Claude Code)
#   3. Installs certbot + nginx plugin if missing
#   4. Creates /opt/jarvis tree (app dir + data dir + log)
#   5. Writes a systemd unit pointing at /opt/jarvis/jarvis-kotlin/bin/jarvis-kotlin
#   6. Writes an nginx vhost reverse-proxying corgflix.duckdns.org -> 127.0.0.1:8080
#   7. Reloads nginx config (test only, does not yet enable TLS)
#
# What the user does AFTER this script:
#   a. scp the gradle installDist tree to /opt/jarvis/jarvis-kotlin
#   b. write /opt/jarvis/.env with JARVIS_AUTH_TOKEN + JARVIS_LLM + OPENROUTER_API_KEY
#   c. run `claude login` (device-code flow) so the Max subscription is bound
#   d. run certbot to provision TLS:
#        certbot --nginx -d corgflix.duckdns.org --agree-tos -m EMAIL
#   e. systemctl daemon-reload && systemctl enable --now jarvis
#
set -euo pipefail

APP_DIR=/opt/jarvis
APP_USER=root
DOMAIN=corgflix.duckdns.org
APP_PORT=8080

require_root() {
    if [[ "${EUID}" -ne 0 ]]; then
        echo "Run as root." >&2
        exit 1
    fi
}

ensure_jdk21() {
    if ! java -version 2>&1 | grep -qE 'version "21\.'; then
        echo "ERROR: JDK 21 not found in PATH. Install with:"
        echo "  apt-get install -y openjdk-21-jre-headless"
        exit 1
    fi
    echo "[ok] JDK 21 present: $(java -version 2>&1 | head -1)"
}

ensure_node() {
    if ! command -v node >/dev/null 2>&1; then
        echo "ERROR: node not found. Install Node 20+ first."
        exit 1
    fi
    local major
    major=$(node --version | sed 's/^v\([0-9]*\).*/\1/')
    if (( major < 20 )); then
        echo "ERROR: Node $major found, need 20+."
        exit 1
    fi
    echo "[ok] Node $(node --version), npm $(npm --version)"
}

ensure_claude_cli() {
    if command -v claude >/dev/null 2>&1; then
        echo "[ok] claude CLI present: $(claude --version)"
        return
    fi
    echo "Installing @anthropic-ai/claude-code globally..."
    npm install -g @anthropic-ai/claude-code
    echo "[ok] claude CLI installed: $(claude --version)"
}

ensure_certbot() {
    if command -v certbot >/dev/null 2>&1; then
        echo "[ok] certbot present"
        return
    fi
    echo "Installing certbot + nginx plugin..."
    apt-get update -y
    apt-get install -y certbot python3-certbot-nginx
}

ensure_app_tree() {
    mkdir -p "$APP_DIR"
    mkdir -p "$APP_DIR/data"        # JARVIS_DATA_DIR (activity.jsonl + wiki.md + embeddings.json)
    touch /var/log/jarvis.log
    chown -R "$APP_USER:$APP_USER" "$APP_DIR" /var/log/jarvis.log
    chmod 700 "$APP_DIR/data"
    echo "[ok] $APP_DIR + $APP_DIR/data + /var/log/jarvis.log ready"
}

write_systemd_unit() {
    cat > /etc/systemd/system/jarvis.service <<EOF
[Unit]
Description=Jarvis life-OS web server
After=network.target nginx.service
Wants=network.target

[Service]
Type=simple
User=$APP_USER
WorkingDirectory=$APP_DIR
EnvironmentFile=$APP_DIR/.env
# Keep HOME at the user's default (/root for root) so 'claude login' done
# interactively writes credentials to /root/.claude — same path the service
# reads from.
# Activity log + wiki + embeddings land at $APP_DIR/data via the
# JARVIS_DATA_DIR env var set in /opt/jarvis/.env. Back up the whole tree:
#   tar -czf jarvis-backup.tgz /opt/jarvis /root/.claude /root/.config/claude
ExecStart=$APP_DIR/jarvis-kotlin/bin/jarvis-kotlin web
Restart=on-failure
RestartSec=5
# Soft memory cap; tune after observing real heap. 512m fits the 2.9G
# headroom the box has after MC.
Environment=JAVA_TOOL_OPTIONS=-Xmx512m -Dfile.encoding=UTF-8 -Dstdout.encoding=UTF-8 -Dstderr.encoding=UTF-8
StandardOutput=append:/var/log/jarvis.log
StandardError=append:/var/log/jarvis.log

[Install]
WantedBy=multi-user.target
EOF
    echo "[ok] /etc/systemd/system/jarvis.service written"
}

write_nginx_vhost() {
    local cfg=/etc/nginx/sites-available/jarvis
    cat > "$cfg" <<EOF
# Generated by tools/vps-install.sh. certbot --nginx will append the SSL
# server block below; do not hand-edit the cert lines.
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;

    # Long timeouts so streaming chat / agent loops do not get cut.
    client_max_body_size 16m;

    location / {
        proxy_pass http://127.0.0.1:$APP_PORT;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Connection "";
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }
}
EOF
    ln -sf "$cfg" /etc/nginx/sites-enabled/jarvis
    if ! nginx -t; then
        echo "nginx config test FAILED; check $cfg" >&2
        exit 1
    fi
    systemctl reload nginx
    echo "[ok] nginx vhost installed; config test passed"
}

main() {
    require_root
    ensure_jdk21
    ensure_node
    ensure_claude_cli
    ensure_certbot
    ensure_app_tree
    write_systemd_unit
    write_nginx_vhost

    cat <<MANUAL

==============================================================
INSTALL COMPLETE. Manual follow-up:
==============================================================

1. Copy distribution from PC:
     # On PC, after gradle installDist:
     scp -r build/install/jarvis-kotlin root@$DOMAIN:$APP_DIR/

   Result: $APP_DIR/jarvis-kotlin/bin/jarvis-kotlin (launcher)

2. Write $APP_DIR/.env (chmod 600!):
     JARVIS_AUTH_TOKEN=<random 32+ chars>
     JARVIS_LLM=claude-max
     JARVIS_DATA_DIR=$APP_DIR/data
     OPENROUTER_API_KEY=<for embeddings; optional>
     JARVIS_PORT=$APP_PORT

   chmod 600 $APP_DIR/.env

3. Bind your Claude Max subscription on the VPS:
     claude login
   (device-code flow: open URL on phone, paste code back)

4. Provision TLS via Let's Encrypt:
     certbot --nginx -d $DOMAIN --agree-tos -m YOUR_EMAIL --redirect

5. Enable + start jarvis:
     systemctl daemon-reload
     systemctl enable --now jarvis
     systemctl status jarvis
     journalctl -u jarvis -f          # tail logs

6. Verify from anywhere:
     curl https://$DOMAIN/healthz      # should print: ok
     curl -I https://$DOMAIN/          # should 302 -> /login

==============================================================
MANUAL
}

main "$@"
